In [5]:
import pandas as pd
df = pd.read_csv('uncleaned_data.csv')

In [6]:
df.head()

,Not at all,1-2 hours,3-4 hours,5-6 hours,More than 6 hours,Strongly agree,Agree,Neither agree or disagree,Disagree,Strongly disagree,...,Always.4,Usually.4,Sometimes.4,Rarely.4,Never.4,Not at all.1,1-2 times,3-4 times,4-5 times,More than 5 times
0,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
2,NaN,NaN,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,5.0,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,1.0,NaN,NaN,NaN,NaN

In [7]:
df.shape

(665, 70)

In [9]:
df.isna().sum()

Not at all           651
1-2 hours            382
3-4 hours            372
5-6 hours            613
More than 6 hours    643
                    ...
Not at all.1         133
1-2 times            553
3-4 times            652
4-5 times            664
More than 5 times    659
Length: 70, dtype: int64